fix the bias missing issue when run fp8/fp4 gemm benchmark (#317)
This PR fixed below error:
TypeError: fp8_gemm() missing 1 required positional argument: 'bias'
when run below test case
python benchmark_gemm_onednn.py --benchmarks fp8

Similar issue for fp4 was fixed too.

Signed-off-by: Bob Zhu <bob.zhu@intel.com>